# Generated by Django 4.2.6 on 2024-04-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='username',
            field=models.TextField(default='hola'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysis',
            name='resultSyntactic',
            field=models.FileField(upload_to='d:\\Alvel\\Desktop\\Uni\\TFG\\tfg\\TFG\\static/media/svg'),
        ),
    ]
