# Generated by Django 4.2.6 on 2024-04-29 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_analysis_username_alter_analysis_resultsyntactic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='resultMorphologic',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='resultSyntactic',
        ),
    ]
